# Generated by Django 3.0.10 on 2021-06-12 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='StoreName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='StorePlace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shelf', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='SparePart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_code_brt', models.CharField(max_length=128)),
                ('order_code_suppliers', models.CharField(max_length=128)),
                ('name_CZ', models.CharField(max_length=128)),
                ('name_EN_DE', models.CharField(max_length=128)),
                ('quantity', models.IntegerField(default=0)),
                ('price_CZ', models.IntegerField(default=0)),
                ('price_EUR', models.IntegerField(default=0)),
                ('main_category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='viewer.MainCategory')),
                ('store_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='viewer.StoreName')),
                ('store_place', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='viewer.StorePlace')),
                ('sub_category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='viewer.SubCategory')),
            ],
        ),
    ]
