# Generated by Django 3.0.10 on 2021-06-12 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sparepart',
            name='description',
            field=models.CharField(default=0, max_length=256),
            preserve_default=False,
        ),
    ]
