# Generated by Django 3.0.10 on 2021-06-14 18:29

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0002_sparepart_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sparepart',
            name='description',
            field=models.CharField(blank=True, help_text='Example: you can write down the type of machine for SP', max_length=256),
        ),
        migrations.AlterField(
            model_name='sparepart',
            name='price_CZ',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20),
        ),
        migrations.AlterField(
            model_name='sparepart',
            name='price_EUR',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20),
        ),
    ]
