# Generated by Django 3.0.10 on 2021-06-20 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0003_auto_20210614_2029'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainCategory1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
    ]
