# Generated by Django 3.0.10 on 2021-06-20 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0004_maincategory1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MainCategory1',
        ),
    ]
