# Generated by Django 3.0.10 on 2021-06-26 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0005_delete_maincategory1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sparepart',
            name='order_code_brt',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
