# Generated by Django 3.0.10 on 2021-06-26 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0006_auto_20210626_1141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sparepart',
            name='id',
        ),
        migrations.AlterField(
            model_name='sparepart',
            name='order_code_brt',
            field=models.CharField(max_length=128, primary_key=True, serialize=False),
        ),
    ]
