# Generated by Django 3.0.10 on 2021-06-26 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0007_auto_20210626_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sparepart',
            name='order_code_suppliers',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
